# Use Joint Trajectory interface to actuate joints of robot
# This file Define output interface of controller manager
# Add parameters to namespace minh_robot
minh_robot:
  # Define interface for joints that activate robot arm
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3

  # Define interface for joint that  activate robot gripper
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_4

